# Static Analyzer Options
#
# For additional info see: https://dart.dev/tools/analysis
#

include: package:flutter_lints_plus/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    missing_required_param: error
    missing_return: error
    record_literal_one_positional_no_trailing_comma: error
  
# Linter rules (see: https://dart.dev/tools/linter-rules)
linter:
  rules:
