name: fitted_box_with_siblings
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/ronjb/fitted_box_with_siblings

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints_plus: ^3.2.0
  flutter_test:
    sdk: flutter
